### ISSUE TITLE
Duplicate apt-get packages installed

### ISSUE THREAD

**Issue by rdmurphy** [texastribune/tribtalk-docker-base#1]
The `python:2.7` image is based on [`buildpack-deps:jessie`](https://github.com/docker-library/buildpack-deps/blob/master/jessie/Dockerfile), which pulls in a bunch of commonly used packages to establish a base. There are a few things being installed that are already available via the upstream image — `curl` and `libpq-dev`, for example.

The `python-pip` package may not be necessary either — [`python:2.7` installs that](https://github.com/docker-library/python/blob/master/2.7/Dockerfile#L47).

**Comment by x110dc** [comment]
I know. I left those as-is in case I had to go back to the Ubuntu image.
